### ISSUE TITLE
ProductResponse field 추가

### ISSUE THREAD

**Issue by gimhanul** [soogung/clone-ohouse-server#13]
### ✨ Describe

ProductResponse에 필요한 Field를 추가해야 합니다.

```
[
    {
        "id": 1,
        "name": "아이닉 대용량 스텐 에어프라이어 3colors",
        "isDiscount": true,
        "discountDegree": 10,
        "mainImage": {
            "imageUri": "https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/166063170056915119.jpg?gif=1&w=1280&h=1280&c=c&webp=1"
        },
        "price": 3000,
        "discountedPrice": 2700,
        "company": "아이닉"
    }
]
```

### ✅ Tasks

- [x] Product Company field 추가
- [x] 가격은 가장 싼 걸로 가져오깅
- [x] 할인 *100 해서 프론트에서 쓰기 좋게 해줘세요
- [x] discountedPrice는 가격 가장 싼 거 * 할인해주고 -> 반올림
